services:
  app:
    build:
      context: .
    container_name: boxbox
    ports:
      - 3100:3000
    command:
      - "--mongo-url=mongodb+srv://boxbox:iv3rX3kJwmaT4m6@clusterboxbox.qx0qn.mongodb.net/"
      - "--mongo-user=boxbox"
      - "--mongo-password=iv3rX3kJwmaT4m6A"
      - "--mongo-db=boxbox"
      - "--access-token-secret=d2f3c1ad624698c8b9"
      - "--refresh-token-secret=d2f3c1ad62398c8b9e7c21af2c20d2f3c1ad624698c8b9"
    volumes:
      - ./public/uploads:/app/public/uploads